# Generated by Django 5.0.4 on 2024-04-18 01:23

import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address_street', models.CharField(max_length=300)),
                ('address_number', models.CharField(max_length=50)),
                ('address_complemento', models.CharField(max_length=50)),
                ('address_cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('address_city', models.CharField(max_length=200)),
                ('address_state', localflavor.br.models.BRStateField(max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadastro de cliente',
                'verbose_name_plural': 'Cadastro de clientes',
                'ordering': ['-date_created'],
            },
        ),
    ]
