# Generated by Django 5.0.4 on 2024-04-19 21:30

import base.models
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customer_address_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('collection', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_size_P', models.PositiveIntegerField()),
                ('stock_size_M', models.PositiveIntegerField()),
                ('stock_size_G', models.PositiveIntegerField()),
                ('stock_size_GG', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('FE', 'Feminino'), ('MA', 'Masculino'), ('IN', 'Infantil'), ('BE', 'Beleza'), ('BA', 'Básicos'), ('JE', 'Jeans'), ('AC', 'Acessórios'), ('ES', 'Esportivos'), ('MO', 'Moda Íntima')], max_length=10)),
                ('sub_category', models.CharField(choices=[('Calça', 'Calça'), ('Blusa', 'Blusa'), ('Blazer', 'Blazer'), ('Shorts', 'Shorts'), ('Camisa', 'Camisa'), ('Camiseta', 'Camiseta'), ('Moletom', 'Moletom'), ('Saia', 'Saia'), ('Vestido', 'Vestido'), ('Top', 'Top'), ('Legging', 'Legging'), ('Calcinha', 'Calcinha'), ('Cueca', 'Cueca'), ('Pijama', 'Pijama'), ('Meia', 'Meia'), ('Sutiã', 'Sutiã'), ('Bermuda', 'Bermuda'), ('Terno', 'Terno'), ('Anéis', 'Anéis'), ('Bolsas', 'Bolsas'), ('Bonés', 'Bonés'), ('Brincos', 'Brincos'), ('Cachecol', 'Cachecol'), ('Carteiras', 'Carteiras'), ('Cintos', 'Cintos'), ('Colares', 'Colares'), ('Óculos', 'Óculos'), ('Relógios', 'Relógios'), ('Lábios', 'Lábios'), ('Olhos', 'Olhos'), ('Rosto', 'Rosto'), ('Unhas', 'Unhas'), ('Perfume', 'Perfume'), ('Banho', 'Banho'), ('Pós-Banho', 'Pós-Banho')], max_length=50)),
                ('color', multiselectfield.db.fields.MultiSelectField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Azul', 'Azul'), ('Rosa', 'Rosa'), ('Vermelho', 'Vermelho'), ('VE', 'Verde Escuro'), ('AE', 'Azul Escuro'), ('Cinza', 'Cinza'), ('Laranja', 'Laranja'), ('Bege', 'Bege')], max_length=10)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('composition', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to=base.models.photo_path_upload_to)),
                ('photo_2', models.ImageField(blank=True, upload_to=base.models.photo_path_upload_to)),
                ('photo_3', models.ImageField(blank=True, upload_to=base.models.photo_path_upload_to)),
                ('photo_4', models.ImageField(blank=True, upload_to=base.models.photo_path_upload_to)),
                ('photo_5', models.ImageField(blank=True, upload_to=base.models.photo_path_upload_to)),
                ('photo_6', models.ImageField(blank=True, upload_to=base.models.photo_path_upload_to)),
                ('sale', models.BooleanField(default=False)),
                ('percentage_discount', models.PositiveIntegerField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastro de produto',
                'verbose_name_plural': 'Cadastro de produtos',
                'ordering': ['-date_created'],
            },
        ),
    ]
