# Generated by Django 5.0.4 on 2024-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_2_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_3_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_4_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_5_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_6_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_main_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
