# Generated by Django 5.0.4 on 2024-04-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
