# Generated by Django 5.0.4 on 2024-04-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
