# Generated by Django 5.0.4 on 2024-04-22 02:02

import django.db.models.deletion
import localflavor.br.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_percentage_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_cep',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_complemento',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_street', models.CharField(max_length=300)),
                ('address_number', models.CharField(max_length=50)),
                ('address_complemento', models.CharField(blank=True, max_length=50)),
                ('address_cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('address_city', models.CharField(max_length=200)),
                ('address_state', localflavor.br.models.BRStateField(max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'verbose_name': 'Cadastro de endereço de cliente',
                'verbose_name_plural': 'Cadastro de endereços de clientes',
                'ordering': ['-date_created'],
            },
        ),
    ]
