# Generated by Django 5.0.4 on 2024-04-22 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_customer_address_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arrival', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='percentage_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_2_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_3_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_4_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_5_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_6_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_size_G',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_size_GG',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_size_M',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_size_P',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.collection'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
